FPTLibrary/Controllers/BookController.cs
using DataAccess.DTO;
using System;
using System.Web.Mvc;

namespace FPTLibrary.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];
            try
            {
                if (userSession == null)
                {
                    return RedirectToAction("Login", "Unauthenticate");
                }
                else
                {
                    if (userSession.RoleID != 2)
                    {
                        return RedirectToAction("DoNotHavePermission", "Shared");
                    }
                    else
                    {
                        return View();
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }
        }
        public ActionResult BookLibraryParialView(int? PageNumber, int? NumberPerPage)
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];

            try
            {
                if (userSession == null)
                {
                    return RedirectToAction("Login", "Unauthenticate");
                }
                else
                {
                    if (userSession.RoleID != 2)
                    {
                        return RedirectToAction("DoNotHavePermission", "Shared");
                    }
                    else
                    {
                        if (PageNumber == null && NumberPerPage == null)
                        {
                            PageNumber = 1;
                            NumberPerPage = 6;
                        }
                        var result = new DataAccess.DAOImpl.BookDAOImpl().Books_GetListByPage(PageNumber, NumberPerPage);
                        ViewBag.CurrentPage = PageNumber;
                        ViewBag.NumberPerPage = NumberPerPage;
                        ViewBag.EndPage = (new DataAccess.DAOImpl.BookDAOImpl().Books_GetList().Count) / NumberPerPage + 1;
                        if (PageNumber > ViewBag.EndPage)
                        {
                            return HttpNotFound();
                        }
                        foreach (var item in result)
                        {
                            item.CategoryName = new DataAccess.DAOImpl.CategoryDAOImpl()
                                .Category_GetDetailByID(item.CategoryID).CategoryName;
                        }

                        return PartialView(result);
                    }
                }
            }
            catch (Exception)
            {

                throw;
            }

        }
        public ActionResult BookDetail(long BookISBN)
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];
            if (userSession == null)
            {
                return RedirectToAction("Login", "Unauthenticate");
            }
            else
            {
                if (userSession.RoleID != 2)
                {
                    return RedirectToAction("DoNotHavePermission", "Shared");
                }
                else
                {
                    var result = new DataAccess.DAOImpl.BookDAOImpl().Book_GetDetail(BookISBN);
                    return View(result);

                }
            }
        }

    }
}

FPTLibrary/Controllers/CartController.cs
using DataAccess.DTO;
using FPTLibrary.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace FPTLibrary.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cart()
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];
            try
            {
                if (userSession == null)
                {
                    return RedirectToAction("Login", "Unauthenticate");

                }
                else
                {
                    if (userSession.UserID != 2)
                    {
                        return RedirectToAction("DoNotHavePermission", "Shared");
                    }
                    else
                    {
                        var result = new DataAccess.DAOImpl.CartDAOImpl().Carts_GetCartByUser(userSession.UserID);
                        ViewBag.User = userSession;
                        return View(result);
                    }
                }

            }
            catch (Exception)
            {

                throw;
            }

        }
        public JsonResult AddBookToCart(long BookISBN)
        {
            var returnData = new ReturnData();
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];


            try
            {

                var result = new DataAccess.DAOImpl.CartDAOImpl().Cart_AddBookToCart(BookISBN, userSession.UserID);

                if (result > 0)
                {
                    returnData.ResponseCode = 99;
                    returnData.Description = "Added Book to cart";
                    return Json(returnData, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    returnData.ResponseCode = -99;
                    returnData.Description = "Some thing went Wrong!! Please try again";
                    return Json(returnData, JsonRequestBehavior.AllowGet);
                }



            }
            catch (Exception)
            {
                returnData.ResponseCode = -999;
                returnData.Description = "System Bussy!! Please try again";
                return Json(returnData, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult BookInCartPartialView()
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];
            try
            {
                if (userSession == null)
                {
                    return RedirectToAction("Login", "Unauthenticate");

                }
                else
                {
                    var cartsOfUser = new DataAccess.DAOImpl.CartDAOImpl().Carts_GetCartByUser(userSession.UserID);
                    var result = new List<DataAccess.DTO.BookDTO>();
                    foreach (var item in cartsOfUser)
                    {
                        result.Add(new DataAccess.DAOImpl.BookDAOImpl().Book_GetDetail(item.BookISBN));
                    }
                    
                    return PartialView(result);

                }
            }
            catch (Exception)
            {

                throw;
            }
        }
       
        public JsonResult CheckOut(string Quantity)
        {
            var userSession = (UserDTO)Session[DataAccess.Libs.Config.SessionAccount];

            var cartsOfUser = new DataAccess.DAOImpl.CartDAOImpl().Carts_GetCartByUser(userSession.UserID);
            var listBook = new List<DataAccess.DTO.BookDTO>();
            double total = 0;
            cartsOfUser.Reverse();

            foreach (var item in cartsOfUser)
            {
                listBook.Add(new DataAccess.DAOImpl.BookDAOImpl().Book_GetDetail(item.BookISBN));
            }
            for (int i = 0; i < listBook.Count; i++)
            {
                foreach (var item in listBook)
                {
                    item.Quantity = int.Parse(Quantity.Split('_')[i]);
                    total += item.Quantity*item.Cost;
                }
            }
            DateTime date = DateTime.Now;

            var createOrder = new DataAccess.DAOImpl.OrderDAOImpl()
                .Order_Create(userSession.UserID, total, date);
            foreach (var item in listBook)
            {
                var createOrderDetail = new DataAccess.DAOImpl.OrderDetailImpl()
                    .OrderDetail_Create(item.BookISBN,item.Quantity,)

            }

            var returnData = new ReturnData();
     
            return Json(returnData, JsonRequestBehavior.AllowGet);
        }
    }
}

FPTLibrary/Views/Shared/DoNotHavePermission.cshtml
@{
    ViewBag.Title = "DoNotHavePermission";
}

<h2>You don't have permission to join this page</h2>

FPTLibrary/Views/Shared/_Layout.cshtml
@{
    var userName = @ViewData["UserName"];
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css?@DateTime.Now.Ticks" rel="stylesheet" />
    <link href="~/Content/Libs/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.js?v=@DateTime.Now.Ticks"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Libs/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/Libs/sweetalert.js"></script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home ", "Index", "Book", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">


                    <li>@Html.ActionLink("MyCart", "Cart", "Cart")</li>

                    <li>@Html.ActionLink("Login", "Login", "Unauthenticate")</li>

                    <li>@Html.ActionLink("Logout", "Logout", "Unauthenticate")</li>


                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>